update @ 2025-11-03 08:22:18 UTC
### 3sat

- 228 pages changed
- 25 pages added
- 10 pages removed
- 289 pages unchanged

### ard

- 197 pages changed
- 5 pages added
- 18 pages removed
- 681 pages unchanged

### ndr

- 300 pages changed
- 38 pages added
- 40 pages removed
- 908 pages unchanged

### ntv

- 582 pages changed
- 3 pages added
- 7 pages removed
- 292 pages unchanged

### sr

- 110 pages changed
- 6 pages added
- 13 pages removed
- 380 pages unchanged

### swr_bw

- 204 pages changed
- 13 pages added
- 18 pages removed
- 760 pages unchanged

### swr_rp

- 213 pages changed
- 28 pages added
- 18 pages removed
- 735 pages unchanged

### wdr

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/socket.py", line 717, in readinto
    return self._sock.recv_into(b)
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www1.wdr.de', port=443): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2025/teletext-archive-2025/src/scraper.py", line 186, in get_html
    return self.session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/requests/adapters.py", line 610, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www1.wdr.de', port=443): Read timed out. (read timeout=20)
```
### zdf

- 191 pages changed
- 40 pages added
- 41 pages removed
- 327 pages unchanged

### zdf-info

- 155 pages changed
- 22 pages added
- 6 pages removed
- 77 pages unchanged

### zdf-neo

- 162 pages changed
- 55 pages added
- 11 pages removed
- 77 pages unchanged