update @ 2025-09-14 08:17:03 UTC
### 3sat

- 222 pages changed
- 18 pages added
- 52 pages removed
- 192 pages unchanged

### ard

- 232 pages changed
- 16 pages added
- 45 pages removed
- 730 pages unchanged

### ndr

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/socket.py", line 717, in readinto
    return self._sock.recv_into(b)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.ndr.de', port=443): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2025/teletext-archive-2025/src/scraper.py", line 186, in get_html
    return self.session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/requests/adapters.py", line 610, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.ndr.de', port=443): Read timed out. (read timeout=20)
```
### ntv

- 220 pages changed
- 19 pages removed
- 653 pages unchanged

### sr

- 157 pages changed
- 12 pages added
- 24 pages removed
- 371 pages unchanged

### swr_bw

- 227 pages changed
- 22 pages added
- 15 pages removed
- 758 pages unchanged

### swr_rp

- 225 pages changed
- 23 pages added
- 16 pages removed
- 715 pages unchanged

### wdr

- 309 pages changed
- 10 pages added
- 33 pages removed
- 596 pages unchanged

### zdf

- 201 pages changed
- 60 pages added
- 50 pages removed
- 330 pages unchanged

### zdf-info

- 164 pages changed
- 16 pages added
- 6 pages removed
- 72 pages unchanged

### zdf-neo

- 156 pages changed
- 51 pages added
- 5 pages removed
- 73 pages unchanged