update @ 2025-12-21 01:21:51 UTC
### 3sat

- 341 pages changed
- 28 pages added
- 6 pages removed
- 255 pages unchanged

### ard

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/socket.py", line 717, in readinto
    return self._sock.recv_into(b)
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.ard-text.de', port=443): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2025/teletext-archive-2025/src/scraper.py", line 186, in get_html
    return self.session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/requests/adapters.py", line 610, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.ard-text.de', port=443): Read timed out. (read timeout=20)
```
### ndr

- 289 pages changed
- 18 pages added
- 7 pages removed
- 955 pages unchanged

### ntv

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/teletext-archive-2025/teletext-archive-2025/update.py", line 42, in scrape
    report = scraper.download()
  File "/home/runner/work/teletext-archive-2025/teletext-archive-2025/src/scraper.py", line 129, in download
    for page_num, sub_page_num, content in self.iter_pages():
  File "/home/runner/work/teletext-archive-2025/teletext-archive-2025/src/sources/ntv.py", line 36, in iter_pages
    data = self.get_html(url).json()
  File "/opt/hostedtoolcache/Python/3.10.19/x64/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
### sr

- 107 pages changed
- 5 pages added
- 1 pages removed
- 424 pages unchanged

### swr_bw

- 270 pages changed
- 17 pages added
- 14 pages removed
- 669 pages unchanged

### swr_rp

- 251 pages changed
- 10 pages added
- 10 pages removed
- 687 pages unchanged

### wdr

- 313 pages changed
- 42 pages added
- 33 pages removed
- 508 pages unchanged

### zdf

- 213 pages changed
- 57 pages added
- 54 pages removed
- 386 pages unchanged

### zdf-info

- 75 pages changed
- 8 pages added
- 1 pages removed
- 156 pages unchanged

### zdf-neo

- 76 pages changed
- 7 pages added
- 1 pages removed
- 123 pages unchanged